// Import from next/font/google using named import
import { Barlow } from "next/font/google";
import "./globals.css";

// Initialize the Barlow font
const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add more weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}> {/* Use the barlow.className */}
        {children}
      </body>
    </html>
  );
}
